### ISSUE TITLE
`@warn ` the user if the physical labels are the same ?  

### ISSUE THREAD

**Issue by mvanzulli** [jorgepz/MshReader.jl#8]
Maybe to add a @warn message if the physical entities labels are the same. 

```julia
Physical Point("_node_fixed-ui") = {9,19};
Physical Point("_node_fixed-ui") = {6,16};
```

Maybe add a warning that the `physical_names` are being merged

**Comment by jorgepz** [comment]
yes, good idea. to add a warning if the label AND the physical object are the same... however. this would be a comment to the user... lo let him/her know that in the geo used that could be optimized... anyway we should check before if gmsh does not check that at the momento of generating the .msh file...

**Comment by mvanzulli** [comment]
Yes I agreee, maybe the user should be responsable for doing it correctly. Or a gmsh responsability.

**Comment by jorgepz** [comment]
I did this test.geo
```
r1 = 2;
ms = 1 ; 

Point(1)  = {0,0,0,ms};
Point(2) = {r1,0,0,ms};
Point(3) = {0,-r1,0,ms};

Circle(1) = {2,1,3};

Physical Point("hola_point") = {1,2};
Physical Point("hola_point") = {2,3};
Physical Line("hola_line") = {1};
```

and got this .msh using gmsh

```
$MeshFormat
4.1 0 8
$EndMeshFormat
$PhysicalNames
2
0 1 "hola_point"
1 3 "hola_line"
$EndPhysicalNames
$Entities
3 1 0 0
1 0 0 0 1 1 
2 2 0 0 1 1 
3 0 -2 0 0 
1 1.110223024625157e-16 -2 0 2 0 0 1 3 2 2 -3 
$EndEntities
$Nodes
4 6 1 6
0 1 0 1
1
0 0 0
0 2 0 1
2
2 0 0
0 3 0 1
3
0 -2 0
1 1 0 3
4
5
6
1.847759064165428 -0.7653668667995119 0
1.414213559153525 -1.414213565592665 0
0.765366862459145 -1.847759065963267 0
$EndNodes
$Elements
3 6 1 6
0 1 15 1
1 1 
0 2 15 1
2 2 
1 1 1 4
3 2 4 
4 4 5 
5 5 6 
6 6 3 
$EndElements
```

so it seems that gmsh does not create two separate labels in the msh file.
